version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: widget-redis

  widget-processor:
    build:
      context: ./backend
      dockerfile: widget-processor/Dockerfile
    container_name: widget-processor
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis

  widget-gateway:
    build:
      context: ./backend
      dockerfile: widget-gateway/Dockerfile
    container_name: widget-gateway
    ports:
      - "8083:8083"
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis

  mock-products:
    build:
      context: ./mock-products/flight-service
    container_name: mock-products
    ports:
      - "9001:9001"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"


volumes:
  redis-data:
